---
title: "Radio Navigation"
---

feels like source for BGS material on radio nav: https://www.scribd.com/document/339377917/Radio-Navigation-pdf    
CAE: https://www.scribd.com/document/823524548/Radio-Navigation-Marked
https://studylib.net/doc/27627103/cae-oxford-easa-atpl-volume-10--radio-navigation

good source: https://aviationtricks.com/radio-navigation/


## Radio Theory

production: oscilating electrical current & aerial   
electrons moving for- and backwards produce electromagnetic field    
field moves away with speed of light

aerial ~ transducer = transforming enery from one type to another: alternating current to free electromagnetic wave = 'radio frequency (RF) energy'

in receiving aerial -> current identical to the originating

transmitter -> tranmitter aerial ~~~ receiving aerial -> receiver -> amplifier -> headset

### Frequency and Wavelength

electromagnetic waves characterised by frequency or wavelength.   
speed of light constnat (in vacuum) 3 * 10^8 m/s

alternating current that cycles once in a second will produce one wave in that time -> wavelength

$$\lambda = \frac{c}{f}$$
doubling frequency -> half the wavelength

note for exam questions: speed of light 3 * 10^8 m/s ~ 300.000 km/s ~ 162.000NM/s

   c
  ---
  f $\lambda$

radio signal, freq 3 kHz -> what is the wavelength?     
3kHz = 3000Hz    
$\lambda = \frac{c}{f} = \frac{3 * 10^8}{3 *10^3} = 10^5 m = 100.000m = 100km$

wavelength of 3.5cm -> what is the frequency?
$f = \frac{c}{\lambda} = \frac{3*10^8}{3.5}*\frac{\frac{m}{s}}{cm}$ = 3*10^8 / 0.035 = 8.57GHz

### Frequency Spectrum

Very      Very Low Frequency    VLF   3-30kHz       100-10km  Myria-metric
Lovely    Low Frequency         LF    30-300kHz     10-1km    Kilo-metric
Maidens   Mediaum Frequency     MF    300kHz-3Mhz   1km-100m  hecto-metric
Have      High Frequency        HF    3-30MHz       100-10m   Deca-metric
Very      Very High Frequency   VHF   30-300MHz     10-1m     metric
Useful    Ultra High Frequency  UHF   300MHz-3GHz   1m-10cm   deci-metric
Sewing    Super High Frequency  SHF   3-30GHz       10-1cm    centi-metric
Equipment Extremely High Freq   EHF   30-300GHz     1cm-1mm   milli-metric

### Phase and Phase Difference

phase angle := positions on a radio wave are expressed in degrees from 0 ... 360    
by definition, measurement of phase angle starts when aomplitude is increasing through zero

in phase = two transmissions with same wavelength/frequency start at same time ~ synchronised.    
out of phase = difference, delta expressed in degrees

note: signals can be in phase with different amplitude, however, wavelength or frequency identical

phase comparison, same wavelength   
avoid cancelling out of signals (i.e., if out of phase by 180deg)

modulation = additional of information to a carrier wave (or transporter)
= process of impressing and transporting infomation by radio waves

modulation can be achieved by i) changing amplitude, ii) changing frequency, or iii) phase of the signal

AM = Amplitude Modulation ~ simplest form of modulation = variation of amplitude of the carrier wave to transmit information

Sidebands   
modulation = imposing intelligence on carrier wave = "heterodyning"   
when 2 frequencies are heterodyned => 2 additional frequencies are created on top of the original carrier wave = sidebands

example: AM signal, carrier wave 400kHz, intelligence of 1 to 3 kHz   
lower side band: 400kHz - 1 kHz & 400kHz - 3kHz

SSB = single sideband transmission = removal of carrier wave and sideband ~ lower power requirement and reduced bandwidth, by convention only the lower sideband     
short range VHF communication systems  DO NOT remove carrier wave.    
long range HF communication systesm use SSB (with suppressed carrier wave)

### Frequency Modulation

instead of varying amplitude, change of wave frequency

FM receiver can clip signal to remove extraneous variations in amplitude.  
FM audio signal = high fidelity reproduction of the original without interference from static.

mixture of frequencies more complex than AM, (virtually) impossible to strip out sidebands   
thus: FM => higher bandwidth, require more power (than AM SSB signal)    
FM transimission requires about 3 times the power required for AM SSB   
and twice the bandwidth

to avoid frequency congestion, FM signals restricted to low power and thus SHORT ranges (becuase of higher bandwidth occupied)

advantage: less static noise/interference
disadvantage:   
  + greater power requirement
  + greater bandwidth, and
  + more complex transmitting and receiving equipment
  
### Phase Modulation

phase modulation allows for the sending of information in form of instantaneous variations in the phase of the carrier wave.   
== Phase-Shift Keying (PSK)

PSK is used in GPS systems, in wireless local area networks LAN, and for bluetooth communication.

### Sending Binary Information

simplest form: morse code

typically achieved by interrupting := keying carrier wave to send a series of dots and dashes.    
~ pulse modulation (morse code, radar)

increasing information needs, more complex binary signals and pulse modulation = Amplitude Shift Keying ASK

FM for digital signals the sidebands are smaller than when sending for instance audio signals, and therefore the disadvantes of FM are less prominten.    
Using FM for digital transmissions is called Frequency-Shift Keying FSK.

Simpest form of phase-shift keying is Binary Phase Shift keying BLSK. This transmits digital information by simply reversing the phase of the carrier wave.

example: binary signal of zeros and ones    
ASK uses an interruped carrier wave (e.g. for the ones)    
FSK varies the frequencies for ones and zeros     
BPSK reverses the phase at every change from one to zero or vice versa.

### Emission Classification

radio transmissions are classified by a three digit ITU code:    
  1. symbol := modulation
  2. symbol := type of modulating signal
  3. symbol := type of information carried
  
NDB    
  NON carrier without modulation
  A1A carrier with keyed morse code modulation
  A2A carrier with amplitude morse code
  
A3E carrier with amplitude modulated speech used for VHF communication

### Polarisation

radio waves are composed of 2 elements: i) electrical or E field, and ii) magnetic field at right angle to electrical field, called H field    
E and H-fields are thus orthogonal and in phase.

vertical polarised wave is a wave in which all the electrical oscillation (E-field) is in the vertical plane.    
Vertical aerial will produce vertical polarised wave requiring a vertical aerial to receive it.   
In analogy, horizontal one will produce horizontally polarised waves.

VHF communication frequencies are vertically polarised and the aircraft aerial are vertical.    
Navigation frequenices (e.g. VOR) are horizontally polarised and the aerials are horizontal, often in V shapre on the fin of the aeroplane.

### Aerials

diploes := simplest aerial vertical or horizontal conductor, the orientation depending on the polarisation, with a length of half the wavelength to be transimitted or received.    
dipole areial ~ $\frac{\lambda}{2}$

monopoles (or single pole) aerial size is effectively half a dipole and therefore has an ideal size of a quarter of the wavelength for optimum efficiency.

top view: ciruclar / omnidirectional ~ aerial transmits equally in all directions.  
side view: monopole aerial transmits well horizontally, but there is an aread overhed where there is no transmission (cone of silence) = no signal.

ideal dipole aerial is half or quarter of the wavelength   


VHF ~ metric band, vertically polarised, with wavelengths from 10m to 1m ==> monotpol receiving aerials placed on the top of the aircraft ~ signal path to/from antenna is not obstructed by parts of the aircraft (top antennas), Length about 2.5 and 25cm.   

VOR aerials are dipoles in the same frequency range, and signals are horizontally polarised.    
=> V shaped aerials on the fin of the aeroplane, each half being a quarter wavelength and therefore in total making up a half wave diploe.

Antenna Shadowing = positioning of aerials is important as the received signal strength is reduced is there is either another aerial or physical obstrauction in the line-of-sight path.   
Another aerial in the way takes energey from the radio wave as it received the signal leaving less for the aerial behind to detect.

### Parabolic Aerials

oldest generation of directional aerials/antenna ~ mathematical shape of parabol => capture of "pencil beam" (or "conical beam")   
not 100% efficient     
generate sidelobes and backscatter, the more efficient, the lower sidelobes and back scatter/energy loss.    
about 2/3 or energy can get lost in sidelobes.    
refrlections from sidelobes can cause interference and confusion to a directional signal.

groubd based radars often make use of kust a section of the aerial to track in only two dimensions.    
The beam is comparatively tight in the horizontal plane, but would not have much definition in the vertical pane.

parabolic antenna typically ground based primary radar systems and aircraft weather radar.

### Phase Array Aerials

modern alternative to parabolic dish = phase array aerial ~ series of conducting elements like small dipoles are arranged in a line and are fed signals in phase with each other.   
interference pattern they produce acts like a pencil beam.

sidelobes are still present, but the advantage of phase array aerials over parabolic aerials is that the energy loss in sidelobes is less to a 1/3 of the total.

examples:   
PSR (parabolic) and SSR (phase array)

slotted scanners or slotted planar arrays ~ (function like) phase array aerials   
vertical dipoles elements are replaced by a series of slots which act as resonante cavities to produce the radio signal.   

reduced energy loss ~ more energy concentration in tighter beam.

most modern aircraft use slotted planar arrays.

note: all dish aerials produce sidelobes. Phase array and slotted planar arrays produce smaller sidelobes.

## Wave Propagation

### Refraction

change in density will result in refraction ~ higher density slower   
amount of refraction ~ change in speed, its frequency, and angle at which it hits the new medium.

change in speed := refractive index (e.g. glass ref ind = 1.5, the higher the freq, the higher the refraction)   
in Ionosphere (refractive index < 1, higher refraction for lower frequencies!)

radio waves are refracted (speed change) due to surface (passing over) or because of the medium they are passing through

### Diffraction

wave passes through a hole ~ circular waveform past the hole    
hole acted as point source and retransmitted the wave

diffraction also happens when passing over sharp objects.

diffraction is greater at longer wavelengths ~ low frequencies

### Reflextions and Re-Radiation

specular reflection ~ simple reflection (mirror like)   
reflection dependent on density and smoothness of reflecting surface material and angle

smooth surface ~ mirror     
rough surface ~ reflection in all directions := diffuse reflection

note: surface reflection dependendent on wavelength/frequency

radar systems -- reflection is an integral part of design -- some return is specular, but most comes from small parts of the taerget airacraft structure acting as little receiving aerials which re-radiate the transmission.    
This effect happens also with water droplets in weather radars.   
Design caution to ensure radar wavelength compatible with target size, i.e. same size or smaller as target.

radar reflection is most likely when the wavelength is compatible with the target size!

### Attenuation

attenuation := loss of signal strength of a (electro-magnetic) wave.    
in vacuum ~ no attentuation   
in atmosphere -> electrions in dust and water droplets absorb some of the energy

atmosphereic attenuaation increases wtih increasing frequency, significant above 1 GHz    

surface attenuation := radio waves passing over Earth's surface loose energy and slow down    
surface atttnuation is greatest and speed is lowest over the ICE CAPS, then desert areas, then over other land, and there is least attenuation over SEA

surface attenuation increases as frequency increases (just at atmospheric attenuation); both affected by same substances, rock and water.

Waves passing through electrically charged atomes at the edges of space known as the ionosphere are also attenuated:   
HOWEVER: ionospheric attenuation increases as frequency decreases


### Space Wave

space wave := line-of-sight wave = standard propagation of all frequencies; range limited by obstructions and curvature of Earth surface.

VHF and EHF only propage with space wave => limited in range.    
Ground reflected waves are also included in this category.

maximum theoretical range of a space wave in UHF or VHF in NM 

$$max_theo_range = 1.23 \sqrt{H_1} + 1.23 * \sqrt{H_2}$$
H1 = height of transmitter, and H2 height of receiver, in FEET ft
range in nautical miles NM

example:   
aircraft at 8000ft communication to ground station. What is max theoretical range of the signal?   

H1(aircraft) 8000ft, ground station (assumed) 0ft/MSL    
max theoretical range = 1.23 (sqrt(0) + sqrt(8000)) = 1.23 * sqrt(80 * 100) ~ 1.23 * (9 *10) = 1.23 * 90 ~ 110NM

### Surface Waves

at lower frequencies, radio waves pass over hills and buildings and are diffracted. 
Effect increased by slower wave front near Earth's surface caused by ground conductivity (resulting in downward component of movement ~ pull to surface).    
=> surface wave follows curvature of Earth

diffraction greatest at low frequencies -> low frequencies tend to form surface waves    
travel distance dpendent on surface attenuation which is lowest at low frequencies and over sea.    
==> surface waves are longest for low(est) frequencies

surface waves    
  + HF band ~ 100NM
  + MF band ~ 500NM
  + LF band ~ 1000NM
  + VLF band ~ 4000NM
  
surface waves and space waves will occur at short range and the combination is called: "ground wave".

surface wave propagation not affected by time of day.

### Sky Waves

sky waves are radio waves refracted from Ionosphere.    
Ionosphere - ionised component of atmosphere ranging from 60-400km above the surface and divided in 3 layers, i.e. D, E, and F layer.

Depth and density of each layer varies with time of day, season and solar activity.

Ionosphere ~ gas molecules (normally with no electrical charge) are split into positive and negative ions.   
Density of ions increases with height and intensity of readiation (solar and cosmic radiation).   
Ionosphere is weaker at night than during day due to change of solar radiation.

Change of ion density -> refraction of radio waves (medium change).    
Most refraction occurs at 125km = E layer.    
Wave of low enough frequency at the correct angle of incidence will be refracted back to earth.     
Some refraction also at F layer.

VHF and higher are certainly refracted if they pass through the Ionosphere, but are not bent enough to come back to Earth.    
I.e., sky waves do not occur at all at VHF and higher frequencies.


### HF Skywaves

lower frequencies = higher refraction in Ionosphere, HF refracted back to Earth as skywave.

minimum skip distance := distance from transmitter to first returning (refracted) skywave; for HF typically 600-1200NM    
near transmitter, HF propagates as space wave and surface wave ~ 150NM

==> area between the end of the sufrace wave range and the first returning skywave (between 150NM and 1000NM) where no signal is received.   
"dead space" or "skip zone".

skip distances increae at night ~ weaker ionosphere ~ less ino density due to lower radiation/no solor radiation => less refraction.    

maximu skip distance occurs when the signal leaves the Earth at a tangent, refracts from the Ionosphere, and returns at a tangent to the Earth's surface.    
Maximum theoretical skip distance from the E layer is about 1500NM.

Note: longer distances due to "multi-hop transmissions" due to Earth refractions/retransmission.

### ML/LF Skywave Interference

ML/LF refract more from Ionosphere = reduced skip distance.
MF/LF have longer surface waves ==> no dead space/skip zone at all around 300-400NM.

==> receiver will pick up both: surface wave and (first returning) skywave which may interfere with each other.

interference: different travel distances ~ variation in phase possible == amplified signal or cancellation.

typically Ionosphere signals move continuously in and out of phase (= increases and decreases) ~ fading == indication that the signal has taking  two paths to the receiver.   

During daytime: signals passing through Ionosphere are subject to inospheric attentuation, greatest at low frequencies.   
==> MF and LF are more attenuated that HF ==> interference unlikely during daytime.   
==> higher fading during night-time (i.e., between dusk and dawn) ~ weaker Ionsophere and associated attentuation.

Skywaves are    
  + reliable in the HF band 
  + do not (normally) occur at VHF and higher
  + cause interference in MF/LF
  
Skywaves are used in HF voice communication and also in HF as part of the ACARS messaging system (long-range communication).

### Sporadic E

skywaves do not "normally" occur in VHF, but intimes of very high solar activity the E layer is much more heavily ionised that usual, called "sporadic E.    
Thus, it becomes dense enough to generate returning skywaves in the lower VHF band.

Unusual, but can lead to unexpected long-range reception in VHF.

### Atmospheric Ducting

Given "right conditions", VHF, UHF, SHF and EHF bands can get "trapped" within a layer in the atmosphere := atmospheric duct.

Atmospheric duct allows for long range propagation over the visual horizon (= atmosphereic ducting or super-refraction).

Near surface ducts ~ marked temperature inversions and a rapid decrease in humidity with height.    
Air mass subsidence (surface high pressure) systems can produce elevated ducts.   

Atmospheric ducting generally unpredictable.     
But, "always" some ducting that extends line-of-sight by about 15%. This is accounted for in the range formula for VHF and UHF.

atmospheric sub-refraction = where atmospheric refraction is less than normal -> causes reduced maximum theoretical range. 

### VLF Propagation

VLF wavelengths in order of tens of kilometers and low frequencies that normally no skywaves will form and completely attenuated by the Ionosphere.    
Surface waves are present up to 4000NM.

Ranges beyond 400NM are formed in VLF because the gap between Ionosphere and Earch acts as natural waveguide.    
This can happen when VLF wavelength is similar to gao height (lower levels of Ionosphere)

Ionospheric ducting := combines very long surface waves with guided waves to reach around the world.

### Static

static interfere with radio signals making communication difficult in HF band and interfering with the operation of navigation equipment.

statis is a natural phenomenon caused by electrical discharges in convective clouds.
Thunderstorms generate huge amounts of electricity and these discharges affect the lower frequencies, becoming insignificant in the VHF band.

MF/LF static can "swamp" signals from NAV beacons in those frequencies, i.e., NDBs => indicators in aircraft point to thunderstorm rather than the NAV beacon.

**precipitation static** when precipitation - particularly rain - strikes aircraft at a different electrical potential, there is a minute discharge of static.   
Again most troublesome in LF and MF bands.

rule of thumb: static and skywaves are unlikely above 30MHz.


### Doppler Effect

sound: change in pitch of engine noise as car passes observer    
water/beach: change in facing waves when moving in or out of water

change in received frequency = Doppler Shift    
Doppler shift proportional to the relative velocity    
indifferent to tranmitter or receiver moving (or both)

+ closing relative velocity produces increase in frequency, i.e., positive Doppler shift
+ if the transmitter and receiver are moving apart, the received frequency is lower, i.e., negative Doppler Shift.

Doppler shift is a small change to the tranmitted frequency, even for jet aircraft.   In most systems small enough to be within bandwidth.    
However, sysgem can be built to "look" for this shift.

Doppler Navigation systems use the Doppler shift in reflected signals to compute the groundspeed and drift of the aircraft.   
More sophisticated systems use this combined with heading from the compass system to compute the aircraft's track and ground speed  providing position readouts.

While mostly superseeded by satellite navigation and intertial navigation, Doppler navigation systems can still be found in some older helicopters.    
Doppler is also sometimes used for hover control.

Doppler is used   
+ some VOR beacon (called Doppler VOR)
+ identify moving targets in some forms of ground based radar called Moving Target Indicators (MTIs)
+ to identify areas of turbulence in some weather radars, and
+ (as one of two methods) to determine receiver's speed in satellite navigation.

### Propagation Summary

+ atmospheric and surface attenuation are greatest at high frequencies
+ ionospheric attenuation is greatest at low frequencies
+ ALL radio frequencies produce SPACE WAVES;    
  SKYWAVES only (reliably) present in HF band, create interference in MF/LF bands
+ SURFACE WAVES start to be significant in HF and get longer with LOW FREQUENCIES
+ atmospheric ducting is occasionally present in VHF and HIGHER    
  ionspheric ducting is present in VLF ONLY
+ static is greatest at LOWest FREQUENCIES

VLF/LF/MF/HF: Surface Wave + Sky Wave
VHF/UHF/SHF: Direct Wave (Space Wave)


Band	Abbr.	Frequency	Wavelength	Aviation Use
Very Low	VLF	3-30 kHz	100-10 km (Myriametric)	-
Low Frequency	LF	30-300 kHz	10-1 km (Kilometric)	NDB/Locator
Medium Frequency	MF	300-3000 kHz	1000-100 m (Hectometric)	NDB/ADF
High Frequency	HF	3-30 MHz	100-10 m (Decametric)	HF Comms, VOLMET
Very High Frequency	VHF	30-300 MHz	10-1 m (Metric)	VOR, ILS Locator, VHF Comms, VDF, Markers
Ultra High Frequency	UHF	300-3000 MHz	100-10 cm (Decimetric)	DME, ILS Glideslope, GPS, Radar Terminal
Super High Frequency	SHF	3-30 GHz	10-1 cm (Centimetric)	AWR, MLS, ASMR, Radio Altimeter
Extremely High Frequency	EHF	30-300 GHz	10-1 mm (Millometric)	-

## NDB and ADF

NDB omni-directional beacon = simplest navigation beacon   
technological progress, NDBs subsequently (not) replaced by VOR/DME, GPS, and IRS

frequencies - WWII ~ requirement to provide information as fars as 600NM over sea, beacons on both sides of Atlantic ~ 1000-1500NM.   
propagation path/wave -> surface waves ==> MF and upper LF bands    
ICAO: 190-1750kHz    
in Europe, NDBs usually operate in the range 280-530kHz   
theoretical ranges over land ~ 300NM (for high power beacons due to higher surface attenuation)

### carrier waves and idents

unmodulated carrier wavem, ITU classification N0N.   
unmodulated signal = best direction finding result    

to make signal identifiable, NDBs use Morse code identifiers of 2-3 letters.    
Idents imposed on the carrier wave in one of 2 ways    
  + NON A1A beacons - older systems interrupe carrier wave to send a series of dots and dashes (keying); the uninterrupted carrier weave identification has the ITU classification A1A, whole transmission referred to as N0N A1A
  
problems:    
  + interrupted carrier wave at MF frequency is not naturally audible - require "extra" device to make it audible; and 
  + use may have erratic bearing indications when the carrier wave signal is being interrupted with Morse code (pauses)
  
### Beat Frequency Oscillators

to make unmodulated signal audioble, the ADF equipment in the aircraft incorporates a Beat Frequency Oscillator (BFO).   
produces freqency slightly removed from the received frequency and the two are then mixed together or herodyned.

mixing of the 2 frequencies produces an audible beat frequency, which is the difference of the 2. Example: oscillator generates signal of 401kHz to match a received signal of 400kHz = heterodyning the two produces additional frequencies at 401kHz + 400kHz = 801kHz and 401 - 400 = 1 kHz.   
Frequency at 1 kHz is the beat frequency and this is an audible tone.

BFO makes the inaudible audible = N0N carrier wave can be heard as a continuous tone which is then interrupted into morse for the A1A ident, then back to continuous tone of the N0N signal again.

A1A idents are nowadays extremely rare. BFO function is still available on modern aircraft with the switches labelled BFO or Tone.

### N0N A2A Beacons

more modern systems do not interrupt the carrier waves, but instead use an amplitude modulated Morse code signal for the identification: ITU A2A.

A2A signal does not need special equipment like the BFO to make it audible.   
A standard ADF receiver will strip the modulated signla off and present it to the aircrew as an audible Morse ident.

NDBs like this are referred to as N0N A2A beacons, N0N for the main carrier wave used for direction finding, and A2A for the intermittent ident.

Amplitude modulation of the morse identifier does still degrade bearing accuracy when the ident is playing - an unmodulated tone is always the best signal for direction finding - but not as much as with the A1A ident.

typically, Holding and airfield approach NSBs: N0N A2A; long range N0N A1A.

### Marine and Other beacons

NDBs are also used by shipping.   
Marine NDBs should not be used for IFR aircraft navigation (and not plotted on aviation charts).

Issue: frequencies for NDBs not exclusively allocated. E.g. long wave commercial radio band between 150ksz and 280kHz which overlaps the NDB band.

ADF receiver can happily pick up the readio stations above 190kHz and you can listen to the (amplitude modulated) broadcast.     
Note: the direction of the source of transmission for these commercial radio stations may ot be used for IFR navigation.

### Receiver Operation

Automatic Direction Finder ADF, replaced an earlier manual system called Radio Direction Finding (RDF, DF).    
Doth systems use rotating loop aerials.    

Technological progress: aerials smaller and faired. modern loop aerial looks nothing like the original. Concept staid the same.

### Loop Aerial

NDB signal vertical polarised -> singal passing over the loop induces an electric current in the vertical parts of the aerial.   
rotation of the loop in line with incoming signal then different phases will be received in each of the vertical bars and current will flow.   
When the aerial is at right angles to the direction of travel, both sides reeive the same phase signal and no current flows.    
If aerial rotated until no current flows, we can be sure it lies at right angles to the wave movement.     
Remaining question: in front of us or behind us.

Loop aerial polar diagram = plan view/aerial from above ~ value of induced current around it as the aerial is rotated we find a figure of eight shape with two clearly fined null points and two less clearly defined maxima.   
The double null is the ambiguity w just identified.

Cardiod - to resolve ambiguity, another vertical aerial is added to the system, the sense aerial.   
The sense aerial receives signals from all directions just like a monopole.   
It is carefully tuned to have a polar diagram diameter that just matches the loop aerial figure of eight polor diagramme.  

When the 2 polor diagrams are combined, the reception charateristics of the 2 aerials can be added and subtraced as appropriate to produce a hear shaped polar diagram : "cardioid". The cardioid has only one null point.

Rotating the loop to find the bearing = rotating the loop areial will rotate the null so that now when no signal is received by the combined aerial, the null is pointing directly at the beacon and the aerial combinaiton will be in line with the incoming signals.

Aerial position is relayed to flight deck instruments.   
These - in its simplest form - shows the relative bearing to the beacon.

### INstrument Displays

* simplest and oldest instruments are fixed card ADFs - sometimes called relative bearing indicators RBIs or radio compasses.

with a fixed card ADF, the bearing of the beacon from the aircraft is determined by adding the aircraft's heading to the relative bearing: magnetic bearing QDM = MH + RB; true bearing QUJ = TH + RB.    
Bearing from beacon/station is obtained by adding/subtracting 180 degrees.

* moving card ADFs - 2nd generation instruments provide a moving compass card so that the aircraft heading, usually magnetic, can be manually set at the top of the instrument.   
POint of needle indicates QDM, tail QDR.

* RMI = 3rd generation of instruments shows magnetic heading of the aircraft continuously at the top of the instrument using feeds from a remote indicating compass. The point of the needle now automatically indicates QDM and tail QDR.   
Radio Magnetic Indicator RMI is standard equipment on most commercial aircraft, either as a standalone insturment or displaying on the EFIS Navigation Display.

RMIs dispaly both ADF and VOR information. On most instruments the two RMI needles can be switched to show either two ADFs, 2 VORs or ADF and VOR.

QDM (head) or QDR (tail) shown are obtained using the aircraft's magnetic heading.   
If true bearings are required, the variation at the aircraft must be used rather than that at the NDB.

Becuase airccraft heading is effectively added to the relative bearing by the instrument to give a QDM, any errors in the aircraft compass system will make both the heading and the QDM and QDR readout at the two ends of the needle unreliable.   
But it will not affect the accuracy of the relative bearing.


### Errors and Accuracy

ADF subject to a number of errors.    
ICAO requirment is an accuracy of -/+5 degrees.   
ICAO Annex 10 requires a monitoring system fo rht beacons to check pwer output and that the ident is present.

* static - all forms of static can affect ADF. In snow and freezing rain, precipitation static reduces the accuracy and attenuation reduces the range of bearing information.
* thunderstorms - TS in the vicinity act as radio beacons and can cause the needle to deviate in their direction. VHF and VORs should be used in preference to ADF. TS can cause largest errors in ADF systems. At the very least, ADF needle will flail around, extreme cases, it will point directly at a very active thunderstorm. (UNPREDICTABLE)
* night effect - although prinicpal propagation of NDBs is ground/surface wave, it is possible for weak sky waves to be returned at night when the inosphere is less dense and inonospheric attenuation correrspondingly less. Change in polarisation (no longer vertical), coming from space at any anglea nd strike the top of the loop aerial where none would be present. --? null is no longer sharply defined and ADF needle hunts reducing the bearing accuracy. 

Night effect can be confirmed by turning the BFO on and listening for the carrier wave increasing and dereasing involume (Fading). Night effect is most likely AT DAWN OR DUSK, no likely at short range (below 200NM) because it is too close to the beacon for sky waves to return.

night effect is sky wave interference from the selected beacon
symptoms of night effect are a hunding needle and fading on the carrier wave   
night effect is greatest at dawn or dusk

* station interference - long ground waves of LF and MF signals mean that signals from other stations on similar frequencies overlap.   
If this occurs, ADF indications may be erratic because there is no sinle null.   
Listening for 2 separate idents. Can be avoided during daytime at least, by only using an NDB within its published rated range.   
At night, returning sky waves can cause rogue signals at considerable range.

rated ranges = published rated ranges quarantee sufficient signal strentgh and freedom from station interference. But without conssidering the effects of skywave interference by day only.

Rated range my be referred to as protected range.

* coastal refreaction - speed of surface wave is affected by surface (faster over water, slower over land) = speed change = wave refraction at low altitude as it passes over coastline. --> refraction always towards the coast (slower side over land pulls wave towards the cost)

the position readout suggest aircraft nearer to the coast than it acutally is (false bearing readout)    
effect increased the wider land-inward the beacon is sited => could be minimised by choosing beacons closer to the coast or flying at higher altitudes.  
can be avoided by taking bearings at right angle from coast when no refraction occurs.

* dip - some Bendix-King aerials suffer from an error called dip. This occurs when the receiver sense aerial is masked by the loop aerial.    
dip results in large bearing errors, only offures in a turn, and is greatest when the NDB is on a relative bearing of 45 or 135 left and right of the nose.

* mountain effect - at low altitudes multi-path signals reflected from or diffracted around terrain can cause erroneous readings. Effect diminishes with height as hills are further from the line of sight and interfere less with the surface wave.

### range 

range of a beacon controlled by its power.    
long range NDB have power output of about 10kW and a range over sea in excess of 500NM   
short range NDB ~ 150NM over land requires an output of 1 kW.

coarse formula:

$$maxrange = 3 * \sqrt{power in Watts}$$
Formula does not include effect of ground conductivity or frequency, only approximate max range.

Doubling the range requires 4 times the output power (due to square root).

NDB bearings have longer ranges over see than over land, because of better surface wave propagation.

range ofa  beacon is not always the same as its rated range!    
ICAO Annex 10 requires the power output of an NDB to generally match its agreed rated range, but an exception is made which allows the power to be greater, if no harmful interference to other facilities will result.    
Thus, rated ranges usually not greater than 200NM, while the effective range of NDBs can be up to 600NM over the sea.

### Types of NDB Stations

ADF equipment will work on any continuous transmission in the frequency range, including commercial radio stations in the MF band.

* **locators** = LF/MF NDB used as an aid to final approach usually with a range of 10 to 25NM (ICAO Annex 10) = low power NDBs at 15 to 40 Watts.    
locators are typically co-located with the ILS outer marker.
* **homing** and **holding NDBs** = beacons intended as an aid to transition from en-route portion to the detination airfield, rated coverage slightly less than 50NM, power output up to 200Watts.
* **en-route** and **long-range NDBs** = raged coverage in excess of 50NM, tend to be in LF end of the allocated frequencies to benefit from longer surface waves.

### Operating the equipment

ADF equipment is normally digitally tuned. -> panel typically for duplicated controls for 2 separate ADF systems (i.e., number 1 and number 2 ADF)

Tuning via selector knobs under frequency display    
turned on by selecting the ANT position (this uses the sense areal position only optimising audio reception for identification but not producing any bearing)

If BFO is required, toggle switches labelled BFO can be seleted to the appropriate system or, on an A2A beacon, select it off by leaving it in the NORM postion.

Once tunig and identification is complete, select ADF on the rotary switch to include the loop aerial and send bearing information to the RMIs.

TEST function to test system. Often ADFs without test facility = no way to check if the instrument has failed. Lack of failure warning indication is often cited as a limitation of older systems.

Select ANT for good audio - but no bearing.
Set    ADF for bearing information.

### Other ADF tuning panels

e.g. A320 - simple(r) to operate.

NAV button to take away control from FMS, then select DF and tune as required.    
Select BFO if required.  Newer systems apply BFO automatically.


### NDB Tracking

ADF needle points towards the beacon = ideal for tracking inbound or outbound from the NDB.   
in still air: point aircraft wher ethe MI indicates    
if wind; allow for wind correction/drift

when aircraft reaches beacon overhead ~ aircraft enters area of weak or no signal called "cone of confusion".   
ADF pointer will rotate around the dial until the signal is (propoerly) restored.

tracking outbound - needle reversed and points to the station, tail of needle shows the QDR = radial the aircraft is on ~ correct for wind drift.

wind changes - with changing wind, tracking and drift correction will be incorrect and the bearing of the NDB will change.    
e.g. wind to zero = drift correction to "strong", QDM wanders as aircraft steers away from bearing/track.

with the heading out by more than the drift, the effect is to push the head of the needle away from the heading bug.

PUSH THE HEAD AND PULL THE TAIL.

example: track 070 away from beacon - heading 060 - no wind    
heading bug "pulls" the tail of the needle towards it (to show the right radial 060).

==> PUSH THE HEAD or PULL THE TAIL

example: RMI showing ADF/yellow 150. Intecept bearing of 130 inbound to NDB in still air; heading bug 095

"push" beyond = answer 170

inbound ISI: soll = 130, is = 150 => from soll to ist + x ~ 170


No allowance for wind/drift and aircrew only follows point of the needle == curved path == curve of pursuit   
homing without allowing for drift is not used in practical navigation because it is inefficient and inelegant. == always correct for drift


### Intercepting a Desired Track

NDB -/+5 deg ~ established on track


## VOR - VHF omni-directional range

VORs more sophisticated than NDBs and operate at shorter range.  
line-of-sight frequencies in VHF band = free from most errors that affect NDBs.

108-117.975 MHz;   
band shared with ILS: 108-112MHz - VOR frequencies allocated at even 100kHz pacing.
112-117.950MHz = only VOR = spacing 50kHz

==> 108.2 and 113.35MHz = VOR frequency; 108.1Mhz ILS (!= VOR)

VOR and Doppler VOR DVOR.

standard VOR (30 revolutions a second) produces a limacon shaped polor diagrame whcih rotates with the dipole at 30 revolutions a second.    
Limacon has no sharp NULL (like cardioid of ADF)

receiver "listening" to signal, amplitude appears to go up and down 30 times a second as limacon rotates (typically clockwise) = received signal is amplitude modulated at 30Hz.    
phase differs of the AM signal depending on the bearing of the aircraft from the VOR. = variable phase signal.    
phase difference is compared to reference phase - omnidirectional reference signal also at 30Hz. Ref signal is frequency modulated FM to be distinguishable.

both signals synced to show phase differnce of 0 for magnetic North 000/360.

receiving aircraft looks at phase differnce between FM reference signal and AM variphase signal and displays it as a radial QDR.

If true bearings are desired, the variation at the staion must be used in the conversion. This is because radials are referenced to magnetic north at the station rather than the aircraft.

DOPPLER VOR = ring of starionary omnidirectional dipoles 13.5m in diameter. VHF signal is switched continously around the ring of aerials so that it appears to come towards the aircraft and then move away. The relative movement of the origin of the signal produces a Doppler shift/shift in frequency that varies with bearing.    
== variphase signal is FM!   
==> reference signal is AM.   this would produce reverse sensing in aircraft receiver ~~ DVOR signal rotates anti-clockwise!!! (reverse the reverse)

aircraft tracking a constant phase difference either inbound QDM or outbound QDR will follow a great circle path

### Cone of confusion

area overhead VOR transmitter where it is not possible to obtain accurate bearing information.

ICAO: confe of confusion 50dep from vertical.

radius of cone can be calculated as 1.2 * height ==> maximum possible diameter of 12 NM at 30.000ft (in reality less)

### Identification

VORs - 3 letter Morse ident modulated at 1020Hz repeating every 10 seconds.    
some beacons have voice identiiers as well.  (this is Stuttgart omni range ... morse code)

if VOR & DME, the DME ident will be heard as a higher pitch 1350Hz every 40 seconds.

### VOR Types

VORs primarily used for en-route IFR navigation.
Many European VORs about 80NM apart to ensure aircraft to stay within confines of airway 10NM wide (1 in 60 rule).

* **terminal VOR** low power beacon used as part of an airfield approach. TVORs often share the lower frequencies with ILS.
* **broadcast VOR** = usually a terminal NAVAID with voice broadcast giving out the airfield weather, the aerodrome terminal information service or ATIS, super imposed on the carrier wave
* **test VOR** (VOT) = low power beacon sited at airfiled (usually in the US) which puts out a constant phase difference of zero in alll directions. ~ allows to test aircraft equipment accuracy on the ground.
VOR test funtion with course set to 000, course deviation indicator should center with FROM indicated, RMI to indicate 180 QDM. Beacon identifier for VOT is a series of dots.

### Airborne Equipment

antenna, receiver, and instrument display    
antenna is horizontal as would suit a horizontally polarised signal, and approximately a quarter of a wavelength long.   
VOR aerials are often seen high on the tails of light aircraft

VOR and ILS usually use the same control panel.    
The aid in use is determined by the frequency selected.

VOR information canbe displayed on an omni-bearing indicator OBI which is used if the aircraft has no electronic compass information, or and RMI and a Horizontal Sitaution Indicator HSI

### Omni Beaing Indicators

omni-bearing selector knob = required bearing    
==> course deviation indicator (hinged at top) showing degrees of displacement from the selected bearing AND    
TO/FROM window/flag indicating wether the selected bearing is a QDR or a QDM.

full deflection = 10 degress

alternative instrument/display - vertical scale/grid for the ILS glideslope, not hinged at one end; here G/S flag (red) as not glideslope signal (as tuned to a VOR)

CHECK FOR SOME SCREEN SHOTS/INSTRUMENT figures

example: 060 selected, TO flag, deviation indicator shows 2 dots left     
==> QDM 060, dot ~ 2deg ==> 2 dots = 4 degs "right" of QDM    
==> bearing to station = 060 - 4 = 056 deg, and on 056 + 180 = 236 radial QDR "inbound" 

Note: display is independent from heading, however it makes sense to fly either TO or FROM a station.

example:   
aircraft heading 075 (M). CDI course 0f 025. VOR indicates TO, needle right deflection.    
In which quadrant to the station defined by what radials?

TO = 025 == QDR 025+180 = 205    
RIGHT == left of course = 025 - 090 = 385 - 090 = 295 (or 205 + 90)

"FLY INTO THE NEEDLE" 

Note: for exam questions: no heading input to OBI - heading is irrelevant regarding location to/from beacon or quadrant.     
selection of intercept radial determines a (next) heading!

example: heading 210, magnetic variation at VOR is 5W and at aircraft 10W.    
CDI shows: TO, deflection right 2 dot, CRS 200   
What radial?

CRS/OBI = 200 ==> target QDR = 020   
course to the right ==> left, 1 dot = 2 deg ~ actual QDR 020 + dot    (2 dot disply => 1 dot = 5deg) ==< actual QDR = 020 + 5 = 025

variation only relevant when TRUE radial desired, station synced signal = station variation, here not asked. 

### Radio Magnetic Indicators RMI

VOR information is usually displaed on RMI.   
This requires an electronic compass feed, and so OBIs are still used in light aircraft.   

RMI feeds compass heading to the top of the dial and the tail of the VOR needle is driven to the detected phase difference on the dial.   
point of the needle indicates the QDM and the tial the QDR.

needles can be associated to NDBs, in this case DME readout would show off flag.

### Horizontal Situation Indicator HSI

HSI usually used togethr with RMI.   
HSI has electronic compass to feed top of dial (showing compass heading)

HSI have rotating center section independent of the compass card.   
Manual selection of particular course/bearing shows deviation from bearing/course similar to OBI; full scale deflection 10 or more degrees; on a 2 dot HSI each dot represents 5 degs; 5 dots ~ 2 degs   
TO/FROM indicator

example: HSI, compass heading 300, course selected 280, TO, deflextion 2 dots RIGHT

==> (tail) target QDR 100, 4 to 5 degrees to our right ==> current QDR = 100 +5 = 105

### Use of HSIs and RMIs

RMI information is stometimes overlaid on the ompass card element of the HSI to combine both instruments; i.e., EFIS versions of HSI.

Example HSI next to RMI, both tuned to same station    
- ac heading 030 - shown on both    
- RMI shows bearing TO station of 060 (QDR = 240)    
- HSI course selected 090, TO flag; deviation at full sale tothe LEFT ~ 090 bearing is more than 10 degrees away

### VOR tracking

VOR tracking can be accomplished using either RMI, OBI, or HSI.

RMI ~ equivalent to NBD - follow bearing (and/or correct for wind)    
OBT indicates in the correct sense (i.e., left/right indications) if the heading is roughly the same as the bearing selected. To track to a beacon turn the course selector knob (OBS) around until TO is indicatoed and the cdi is central.    
== selected bearing - still air heading to beacon. Adjust for drift and follow CDI as commands.

Heading instructions are deliberately vague, using words like turn left a little, because the readial sensitivity of the instrument increases the closer the beacon.   
--> smaller corrections, if closer to beacon.

tracking FROM a beacon:   
- OBS until FROM and CDI centered    
- turn aircraft to a heading that matches the selected bearing   
- correct for drift
- follow command

intercepting a bearing on either the OBI or HSI: start by setting up the required bearing wiht the OBS of course selector.

### Procedure Turns

VORs and NDBs can be used to execute procedure turns.   
These are formal turning paths used to reverse the direction as part of a procedural approach.

Most common: 45/180 procedure

- start at facility or fix with track guidance - either timed or limited by radial or DME distance    
- 45 degrees turn to the LEFT    
- timed straight outbout leg without track guidance; CAT A and B: 1 min, CAT C,D, and E: 1:15min = 75 secs    
- 180 turn to the right to intercept inbound track

### Errors and Accuracy

VOR is free from sky wave interference and coastal refraction because of its higher frequency and line-of-sight transmission.   
Bending of signal by structure of aeroplance does not accect the indicated bearing, i.e. no quandrantal error.

Designated operational coverage DOC of a VOR, the range, sector, and altitude where freedome fom interfreence is guqanranteed, is given in the AIP.   
Unlike protected range of NDBs, this is valid both by day and night.   
Outside DOC interfreence from other stations is possible.   
DOC is sometimes referred to as "service volume".    

ICAO estimate the overall fixing accuracy of VORs to be -/+5 degrees on 95% of occasions.

When flying VOR approaches, ICAO Doc 8168 required the aircraft to be within half a scale deflection, i.e., 5 degrees of the selected bearing, to be considered "on track".

### Scalloping and Site Error

reflections from terrain and mane made obstructions can cause errors as 2 signals with different phase differences interfere, "site error".

Site errors cause VOR indicator to move rapidly from side to side. On a RMI it will make the indicator needle wobble.   
This effect is known as "scalloping".   

Scalloping different from beam bends wihch are also caused by reflections from buildings, but which are more predciable slight curves within the system tolerances.   
Where Scalloping is known to occur, it is notified in the COM sectino of the AIP and on approach plates.

Conventional VOR variphase signals are continuously transmitted through 360 and differing amplitude.    
" continuous"  reflection by obstructions near transmitter.   
DVOR variphase signal is switched around much larger aerial, and is likely to reflect from an obstruction and hit the aircraft receiver only for a small part of its cycle.   
Thus, DVOR suffer less from multipath signals; and the reason given is because of the larger aerial.

### Multipath Signals and Mountain Effect

Reflections from terrain at a distance from the transmitter may be referred as 'multipath signals', the error arising may unusually be referred to as mountain effect, although that name is normally reserved for the equivalent NDB error.

### Atmospheric Ducting

atmospheric ducting can lead to synchronous transmissions even within the DOC.   
Ducting is inherently unpredictable, so no allowance can be made for it, illustrating the need to check the station ident whenever a beacon is used.

Scalloping causes rapid deflections that can not be followed by an aircraft.

### Power and Range

output power of tranmitter impacts range: 200Watts -> up to 200NM, 50 Watts only good for short range transmissions.

max theoretical range: = 1.23 sqrt(H_t) + 1.23 * sqrt(H_rx)

### Equipment Errors

ICAO Annex 10 requires VOR transmitters to be monitored to make sure they put out bearings to at least an accuracy of -/+ 1degree.   
Should the monitor detect a greater bearing error, transmitter to be shut down and stanby transmitter to be brought online.   
Station to be shut down, if signal strenth drops by more than 15% or if monitor fails.

During the transfer period the sation ident either ceases or is replaced by a continuous tone.   
The ident is resumed when the standby tranmitter is operating within limits.


## ILS

NEXT: ILS chapter




## QUESTIONS
c/f = 3 * 10^8 / 75MHz = 3 * 10^8 / 75 * 10^6 = 3/75 * 10^2 = 300/74 ~ 4

c/lambda = 3 * 10^8 / 12cm = 3 * 10^8 / 12 * 10^-2 = 3/12 * 10^10 = 30/12 * 10^9 ~ 2.5 * 10^3 * 10^6 = 2500MHz


range NDB    
- transmitting power: more power, lomger range     
- frequency: lower freq, longer ground wave
- terrain: "lower terrain" = sea, longer range