---
title: "090-communications"
---

## Radio Theory

production of radio wave: oscillating electrical current and an aerial (antenna)   
electrons moving back and forth in aerial produce changing electrical field   
electrical field moves "away" from aerial at speed of light   
"receiving" aerial induces "identical" current   
amplifiers and filters compensate for power loss of signal at receiving end

transmitter --> transmitter aerial ........ receiving aerial --> receiver --> amplifier -> headset

waves are referred to in terms of frequence or wavelength   
speed of light ~ constant (in vacuum) 300.000.000 $\frac{m}{s}$ = $3 * 10^8 \frac{m}{s}$.
= $162.000 \frac{NM}{s}$

cycles per second = frequency   
doubline frequency will halve the wavelenght, i.e. 2 cycles per second

1000Hz = 1 kHz, 1.000.000Hz = 1MHz, 1.000.000.000Hz = 1GHz

wavelength $\lambda = \frac{c}{f}$

note: for calculations use right units:    
* wavelength $\lambda$: metres
* frequency $f$:        Hz = $\frac{m}{s}$

example: radio signal of 3kHz - find wavelength: $\lambda = \frac{c}{f} =\frac{3 * 10^8}{3 * 10^3} = 10^5m = 100km$

Radio signal has wavelength of 3.5cm. What is the frequency?
$\lambda = 3.5 cm = 3.5 * 10^{-2}m$
$f = \frac{c}{\lambda} = \frac{3 * 10^8 m/s}{3.5 * 10^{-2}m} = \frac{3}{3.5}*10^{10}\frac{1}{s}$
$f = 0.857 * 10 * 10^9 Hz =8.57 GHz$

### Frequency Spectrum

radio spectrum is part of electromagnetic spectrum and covers frequencies from 3kHz to 300GHz.   
spectrum browken down into 8 bands ranging from Very Low Frequencies VLF to Extremetly High Frequencies EHF.

military uses upper VHF and UHF bands for communications.   
civil agencies use the VHF badn from 118MHz to 137 MHz.

Channel spacing now -- in Europe -- 8.33kHz (used to be 25 kHz) ~ increase in number of channels.   
reception (power) usually good when in range

range affected by    
* power of transmitter
* height of transmitter and receiver
* obstracutions between transmitter and receiver.

civil communication is also conducted on HF frequencies between 2.8MHz and 22.0MHz.
These frequencies give long range, over the horizon capbailty

>>> add frequency and band table <<<<

mnemomic: Very Lovely Maidens Have Very Useful Sewing Equipment

### Maximum Theroretical Range

max theoretical range NM = $1.23 * \sqrt{height\ transmitter(ft_{AMSL})} + 1.23 * \sqrt{height\ receiver(ft_{AMSL})}$   
range in NM ~ both heights in feet AMSL

range represents line of sight plus an element of ducting.    
Ducting is a phenonmenon in which - under certain atmospheric condistion - a radio wave may be 'ducted' or 'guided' along a narrow horizontal layer following the Earth's curvature.    
This invariably results in an increase in the wave's transmission range.

Example: maximum distance for a VHF contact over flat terrain at FL100?   
no info on receiver ~ h2 := 0    
FL100 ~ 10.000ft AMSL   
==> $1.23 * \sqrt{10^4} = 1.23 * 10^2 = 123NM$

What is the approximate VHF range for an ac at FL80 and an aeronautical station at 325ft MSL?

range NM = $1.23 * \sqrt{8000} + 1.23 * \sqrt{325}$    
= $1.23 * \sqrt{9*9*10^3} + 1.23 * 18 = 1.23 * 9 * 10 + 22.14 = 110,7 + 22,14 = 132NM$

ac range is 115NM, FE 169ft. Min FL to receive VHF signal?

$R = 1.23 \sqrt{H1} + 1.23 \sqrt{H2}$    
$\frac{R - 1.23 \sqrt{H1}}{1.23} = \sqrt{H2$    
$H2 = (\frac{R - 1.23 \sqrt{H1}}{1.23})^2$
$H2 = (115 - 1.23 * 13)^2/(1.23)^2$   
$H2 = (99 / 1.23)^2 = 6460ft = FL65$

### Power

power output of a transmitter affects its range.   
200W outputs --> 200NM, 50NM --> short range transmissions.

Doubling of range requires 4 * power.

==> if ac twice as far from transmitter, received power  1/4 of original strength

### Attenuation

Attenuation is the loss of signal strength of a wave.   
In vaccum there is no attenuation as the radio wave has nothing to give up its energy to.   
Waves passing through atmosphere, dust and water droplets absorb some of the energy = atmosphereic attenuation.

attentuation increases with increasing frequency   
attentuation significant > 1 GHz

waves passing over Earth's surface lose energy and slow down.   
surface attentuation is greatest and speed is lowest over the ice cap, then desert areas, then over other land; least attentuation over sea

surface attentuation increases as frequency increases similar to atmosphereic attentuation.   
rock and water affect both.

waves passing through layers of electrically charged atoms at the edge  of space, i.e., ionosphere, are likewise attenuated.   
ionospheric attenuation increases with lower (decreasing) frequencies (i.e., opposite effect)

attenuation is the loss of power in waves.   
atmospheric and surface attenuation is greatest with high frequencies.   
ionospheric attenuation is greatest at low frequencies.

### Adding Information

frequency of a wave on its own is not audible - cannot be heard as a single tone.
any information to be transmitted myst be "laid on top" of the carriert wave before transmission and decoded by the receiver.   
This process is known as modulation and demodulation.

#### Amplitude Modulation

simplest form of modulation := vary the strength or the amplitude of the carrier wave to transmit inforamtion.   
VHF, UHF, and HF comms use amplitude modulation AM.

modulation is the addition of information to a carrier wave.

#### Frequency Modulation

alternative form of modulation ~ vary the frequency. == frequency modulation FM

although FM receiver wil pick up the same interference and static with the signal as an AM receiveer, it has the capability to "clip" the signal to remove any extraneous variations in amplitude.   
The variation in frequency which can carry the intelligence are unaffected.   
Thus, an FM audio signal will produce a high fidelity reporuductionof the original without interference from static.

FM more complex - but reduces static.

#### Pulse Modulation

information such as Morse signals can be transmitted by interrupting the carrier wave to send a series of dots and dashes.   
more complex systems can use pulse modulation to send digitised information in a binaray code.

PM sends digital data or morse code.


### Summary

radio waves are the name given to a specific band of frequencies of electromagnetic radiation.   
radio waves travel at the speed of light, approx 300.000.000m/s = 3*1-^8 m/s.

radio waves are generated by passing an oscillating electircal current through an aerial.   
each oscillation produces one wave

relationship; wavelength $\lambda$ = $\frac{c}{f}$

information is carried by altering the radio wave's freququency or its amplitude, i.e., the wave is "modulated".

radio frequency spectrum is divided into 8 bands ranging from very low to extremely high frequency.   
Factors affecting the range of VHF and UHF signals are:    
* power of the transmitter
* height of the transmitter and the receiver
* obstructions between transmitter and receiver

The maximum theoretical range of a VHF or UHF signal is given by: max range (NM) = $1.23 \sqrt{H1(ft\ AMSL)} + 1.23 \sqrt{H2(ft\ AMSL)}$

VHF -> A3E ~ Amplitude Modulation
VHF ~ line of sight (air wave)


## Categories of Messages

"aeronautical mobile service" := (ICAO) air to air or ground to air communications

aeronautical station := ground station    
"aeronautical fixed service" := communication between ground stations

### AFTN

aeronautical fixed telecommunication network (AFTN) ~ network of text type messaging between ground (fixed) stations

AFTN ~ world wide system of aeronautical fixed circuuits  -> exchange of messages and/or digitla data between aeronautical fixed stations having the same or compatible communication characteristics

telecommunication := any transmission, emission, or reception of sign, signals, writing, images, and sounds or intelligence of any nature by wire, radio, optical or other electromagnetic systems.

### Message Categories

radio messages in the aeronautical mobise serveice fall into one of 6 different categories.    
priority dependent on category

* distress calls, distress messages, and distress traffic "MAYDAY"
* urgency messages, incld. messages preceded by medicatl transport signal "PAN PAN" or "PAN PAN MEDICAL"
* communication related to direction finding
* flight safety messages
* meteorological messages
* flight regularity messages

### Distress Messages

distress := ac or pax are threatened by serious and/or imminent danger and require immediate assistance

ac: 
* "MAYDAY" preferrably 3 times   
* MAYDAY call on frequency in use, 121.5MHz or other distress frequencies when unable to contact aeronautical station on freq in use   
* under radar contact maintain allocated SSR code unless instructed to change to 7700

MAYDAY message to consist of as many as possible    
* name of station being addresses (if time and circumstances permit)
* identification of aircraft
* nature of distress
* intention of person in command
* present position
* level or altitude
* aircraft heading

response ~ first station acknowledging distress message   
* immediately acknowledge distress message
* take control of communications or clearly transfer that responsibility, advising the aircraft if a transfer is made;
* take immediate action to ensure that all necessary information is made available, as soon as possible to 
  + ATS unit concerned;
  + aircraft operating agency concerned, or its representative, in accordance with teh pre-etablished arrangements; and
* warn other stations, as appropriate, to prevent the transfer of traffic to the frequency of the distress communication

Imposition of silence

The station in distress, or the station in conteol of distress traffic, may impose silence, either on all stations of the mobile service in the area or on any station that interferes with the distress traffic.    
It may address these instructions: "TO ALL STATIONS", or to one station only, according to circumstances by ".... STOP TRANSMITTING" together with the distress signal "MAYDAY".

action by all "other" stations

distress comms have priority over all other communications   
stations aware of a distress situation/communication must not transmit on the frequency concerned, unless    
* distress is cancelled or distress traffic is terminated
* all distress traffic has been transferred to other frequencies known as discrete frequencies DEF
* station contolling communications gives permission
* it is obliged to render assistance

termination of distress communication and of silence

ac no longer in distress, mut transmit message cancelling the distress condition

distress communication and silence conditions are terminated by ATC transmitting a message including the words DISTRESS TRAFFIC ENDED on frequencies being used for distress traffic

AC: CANCEL DISTRESS   
ATC: DISTRESS TRAFFIC ENDED to all stations


frequencies can be truncated 119.100 := ONE ONE NINEr DECIMAL ONE

only the station controlling the communication can terminate distress communication/silence

### Urgency Messages

urgency := condition concerning the safety of an aircraft or other vehicle, or of some person on board or within sight, but which does not require immediate assistance.

PAN message also used for medical transports.    
medical transports defined in 1949 Geneva Conventions and Addional Protocols := any means of transportation by land, water, or air; whether military or civilian, permanent or temporary, assigned exclusively to medical transportation and under the control of a competent authority of a party to the conflict.

ac reporting urgency condition:

in general, urgency message preceded by the phrase PAN PAN, preferable spoke 3 times

PAN prefix also used by medical transports.

urgency message to be sent by ac reporting urgency condition on the air-ground frequency in use comprising    

* name of station addressed
* identification of aircraft
* nature of urgency
* intention of the person in command
* preswent position, level / altitude, and heading
* any other useful information

action to be taken in reply

first station receiving urgency message shall

* immediately acknowledge the urgency message
* if necessary, exercise control of communications;
* take immediate action to ensure that all necessary infromation is made available, as soon as possible to:
  + ATS unit concerned; and
  + the aircraft operating agency concerned, or its representative, in accordance with the pre-established arrangements
  
Urgency communication have priority over all other commununications, ecept distress, and all stations should teake care not to interfere with the transmission of urgency traffic

action by aircraft used for medical transports

PAN PAN * 3 MEDICAL

* callsign or other recognised means of identification of the medical transports
* position of the medical transports
* number and type of medical transports
* intended route
* estimated time en route and of departure and arrival, as appropriate
* any other information such as flight altitude, reaio frequeniceis guarded, languatges used, and secondary surveillance radar modes and codes.


### Direction Finding DF

some VHF ground stations are equipped with automatic direction finding VHF DF    
military stations may provide VHF DF or UHF DF

bearing information can be provided on request expressed as either a magnetic or true direction either to or from the station.   
Bearings from 2 DF stations can provide a fix.   

* QTE ~ true bearing from the station  (True Emanation)
* QUJ ~ true bearing to the station
* QDR ~ magnetic bearing from the station (Direction on Radial)
* QDM ~ magnetic bearing to station (Direction to Mama)

stations providing VHF DF are listed in AIP.   
Some VDF are not available for enroute navigation pruposes except in emergency.   
VDF bearing will only be given when conditions are satisfactory and radio bearings fall within calibrated limits of the station. 
If a readio bearing cannot be given the pilot will be told why.

note: bearing accurace of -/+5deg most common, i.e., class not given

VDF fxing --> VDF from a single station do not provide a position fix. To objtain a fix several CDF stations must be operating on the same frequency at the same time.   
This only occurs on the VHF Emergency Frequency 121.5 MHz.

Fixing accuracy    
* class A ~ accurate within  5NM
* class B ~ accurate within 20NM
* class C ~ accurate within 50NM
* class D ~ accurate less than C (> 50NM)


### Flight Safety Messages

flight safety messages include

* movement and control messages
* messages originated by an aircraft operationg agency or be an aircraft, of immediatee concernt to an aircraft in flight
* meteorological advice of immediate concern to an ac in flight or about to depart (individually communicated or for broadcast)
* other messages concerning aircraft in flight or about to depart

"most" communication between ATC and ac fall into this category.


### Meteorological Messages

meteorological messages are messages to or from aircraft which contain meteorological information other than that listed as flight safety message.

### Flight Regularity Messages

flight regularity messages comprise:

* messages regardin the operation or maintenance of facilities essential for the regularity of aircraft operation;
* messages concerning the servicing of aircraft
* instructions to aircraft operating agency representatives concerning change in requirements fror passengers and crew caused by unavoidable deviations from normal operating schedules. Individual requirements of passengers or crew shall not be admissible in this type of message.
* messages concerning non-routine landings to be made by the aircraft;
* messages concerning aircraft parts and materials urgently requireed;
* messages concerning changes in aircraft operating schedules.

### Summary

AFTN provides communication between ground stations using the AFTN network

6 categories of messages   
* distress ("MAYDAY")
* urgency ("PAN PAN") or PAN MEDICAL transport
* direction finding DF
* flight safety
* meteorological
* flight regularity

distress := ac or pax are threatened by serious and immediate danger and require immediate assistance    
urgency := condition concerning the safety of an ac or its pax which does not require immediate assistance (!= distress)

VHF ground stations may provide automatic direction finding
  + class A ~ accurate to -/+2deg
  + class B ~ most common, accurate to -/+5deg

VDF position fix from 2 or more stations are also categories
  + class A ~ accurate within 5NM (9.3km)
  + class B ~ accurate within 20NM (37km)




## Radio Techniques

standardised R/T --> reduce risk of misunderstanding/interpretation   
ICAO recommends "standard phraseology" or plain language.

"mach's Maul auf & hör bald auf!", adequate speed, no fillers, PTT   
no response ~ wait about 10secs   
do not use OVER or OUT (only to clarify, if needed)

stuck mic ~ transmit button is held of stuck ~ frequency unusable by others

### Transmission of Time

times are given in UTC   
usually only "minutes" (as hour known) - use hour if there is any possibility of confustion

### Transmission of Letters

exception of telephony designator and the type of aircraft, each letter in the aircraft callsign should be spoken separately using the phonetic spelling.

### Transmission of Numbers

3500  THREE THOUSAND FIVE HUNDRED
25000 TWO FIVE THOUSAND

use DECIMAL

### Standard Words and Phrases

ACKNOWLEDGE let me know that you have received and understood this message
AFFIRM      yes
APPROVED    permission for proposed action granted
BREAK       indicate separtion between portion of the messge
BREAK BREAK indicate separation between messages transmmitted to different aircraftin a very busy environment
CANCEL      annul previously transmitted clearance
CHECK       examin a system or procedure; no answer is normally expected
CLEARD      authorised to proceed under the conditions specified
CONFIRM     I request clarification of ...
CONTACT     establis radio contact with ...
CORRECT     true or accurate
CORRECTION  an error has been made in this transmission (or message indicated) ... the correrct version is ...
DISREGARD   ignore
HOW DO YOU READ
I SAY AGAIN I repeat for clarity or emphasis
MAINTAIN    continue in accordance with the condition(s) specified or in its literal sense (e.g. MAINTAIN VFR)
MONITOR     listen out on ... (frequency)
NEGATIVE    no or permission not granted, this is not correct
OUT         this exchange of transmission is ended, no response expected
OVER        my transmission ended, I expect a response from you
READ BACK   repeat all, or the specified part of this message back to me exactly as received
RECLEARED   a change has been made to your last clearance and the new clearance supersedes your previous clearance or part thereof
REPORT      pass me the following information
REQUEST     I wish to know ... I wish to obtain ...
ROGER       I have received all of your last transmission
SAY AGAIN   repeat all, or the following part of your last transmission
SPEAK SLOWER  reduce your rate of speech
STAND BY    wait and I will call you
UNABLE      I cannot comply with your ... (request, instruction, ...), normally followed by reason
WILCO       I understand your message and will comply
WORDS TWICE - as a request: communication is difficult, please send every word/group twice
            - as information: as comms are difficult, each word/group will be sent twice

### Callsigns

aeronautical stations are identified by the name of the location followed by a suffic.   
suffix indicates type of unit or service

if satisfactory communication has been established and provided that it will not be confusin, the name of the location or callsign suffix may be omitted: LANGEN APPROACH --> LANGEN or APPROACH

* area control center ACC   CONTROL
* radar (in general)        RADAR
* approach control          APPROACH
* approach control radar arrivals   ARRIVAL
* approach control radar departures DEPARTURE
* aerodrome control         TOWER
* surface movement control  GROUND
* clearance delivery        DELIVERY
* precision approach radar  PRECISION
* direction finding station HOMER
* flight information service  INFORMATION
* appron control/management APRON
* company dispatch          DISPATCH
* aeronautical station      RADIO

### Aircraft Callsign

commercial aircraft may use either their aircraft registration or -- more commonly -- an R/T designator approved by ICAO plus the flight number.   
For example, British Airways designator is "SPEEDBIRD" (BAW), Aer Lingus "SHAMROCK"

change of callsign --> likelihood that confusion may occur because of similr callsigns, an aircraft may unusually, be instructed by an air traffic control unit to temporarily change the type of its callsign

ATC: CHANGE YOUR CALLSIGN TO .... [UNTIL FURTHER ADVISED]

REVERT TO FLIGHT PLAN CALLSIGN .... [AT significant point]

Aircraft in the HEAVY WTC, MTOW > 136.000kg, include HEAVY immediately after the aircraft callsign in the initial call to the aerodrome control tower and the approach control unit   
SUPER in case of A380.


### Summary

times are given in UTC - usually only minutes (unless risk of confusion)

aeronautical stations are identified by the name of the location followed by a suffix. suffix indicates the type of unit or service provided

general aviation aircraft and private ac use the aircraft registration as the callsign.   
commercial aviaition normally use R/T designator approved by ICAO followed by the flight number

aircraft is not allowed to change its type of callsign or alter its callsign during flight other than adopting ATC's abbreviation.   
If necessary, ATC may instruct an ac to change its callsign.

Initial call to an aerodrome control tower or approach control unit, an ac in HEAVY WTC must include HEAVY (or SUPER) immediately after the callsign.



## Radio Phraseology

### VFR Operating Minima

A flight can be conducted under either VFR or IFR.   
All flights can be operated under IFR, but only some flights -- depending on the weather conditions and the airspace -- can operate VFR.

Where permitted, VFR flights must comply with weather minima

No VFR in airspace A!

airspace class              B   C   D   E   F   G
* at and above 10.000ft     visibility 8km, 1500m horizontally and 1000ft vertically clear of cloud
* below 10.000ft and
  above 3000ft MSL/1000ft GND visibility 5km, 1500m horizontal, 100 vertical clear of cloud
* below 3000ft MSL/1000ft GND vis 5km       vis 5km
                              -- 1500m      clear of cloud
                              | 1000ft      GND in sight
                              

### IFR Aerodrome Minima

formally: no weather minima for IFR flights, but rules relating to destination and  alternate aerodrome weather

an IFR flight must NOT be commenced unless the forecast for the landing airfield is at at or above the aerodrome operating minima for the estimated time of arrival ETA -/+1 hour.   
Where a destination alternate is required, at least one destination alternate aerodrome must, at the estimated time of arrival -/+1 hour meet the more stringent planning minima.

if weather reports or forecasts for the destination inidcate that tat ETA -/+1 hour the weather will be below the applicable minima, or is no meteorological information is available, 2 destination alternates are required.

Having commenced the flight, a commander shall not continue towards the planned sttination unless the latest inforation available indicates that at the estimated time of arrival the wether conditions at the destination, or at least one of the destination alternate aerodrome, are at or above the applicabel aerodrome operating minima.

### General RT Procedures

first contact: full callsign, both ac and ground/aeronautical station

message repitition: SAY AGAIN, SAY AGAIN ALL AFTER ..., SAY AGAIN ALL BEFORE

station identification: station called uncertain of the identification of the calling station, the calling station should be requested to repeat its callsign until identification is established.   
After contact is established, continuous communicaiton may b e performaned without further identification or call sign until termination of the contact, provided that no confusiotn or ambiguity will result.

error in transmission: use CORRECTION, for full message: CORRECTION, I SAY AGAIN ...   
if reception is likely difficult, important elements of the message should be spoken twice.

broadcasting: ALL STATIONS, no reply expected unless individual stations are subsequently called to acknowledge recept.

transfer of communications: frequency change, ATC will pass the instruction with the name and frequency of the (next) ATS unit

conventions: following words can be omitted provided no confusion or ambiguity   
* SURFACE in relation to surface wind direction and speed
* DEGREES in relation to radar headings
* VISIBILITY, CLOUD, and HEIGHT in meteorological reports
* HECTOPASCALS when giving pressure settings
  hectopascal to be appended when transmitting pressure setting below 1000hPa, or wehre confusion or ambiguity may otherwise result
  
excessive use of courtesises should be avoided

IMMEDIATELY should only be used when immediate action is required for safety reasons.

### ISSUE OF CLEARANCE AND READ BACK REQUIREMENTS

clearance may vary in content from a brief landing clearance to a detailed description of the route and levels to be flown

ALL ATC clearances MUST BE READ BACK.   
Strict adherence to read back procedures ensures that the clearance has been received correctly, but also that is was transmitted as intended.   
Serves as a check that the right aircraft, and only that aircraft, will take action on the clearance.

MUST BE READ BACK IN FULL:    
* taxi instructions
* clearances to enter, land on, take off from, cross, backtrack, and hold short of the runway in use
* runway in use
* heading instructions
* speed instructions
* level instructions
* altimeter settings
* SSR codes
* airways or route clearances
* VDF information
* frequency changes
* type of radar service
* transition level (TL shall be read back if given by ATIS broadcast)

other clearances and instructions must be read back or acknoweledged in a manner that clearly indicates that they have been understood and accepted, an abbreviated format may be used.   
an ac should normally terminate the read back with its callsign.

if aircraft readback is incorrect, ATCO shall transmit NEGATIVE followed by the correct version.

inability to comply --> if there is doubt whether a pilot can comply with an ATC clearance or instruction, the controller may follow the clearance or instruction by the phrase: IF NOT POSSIBLE, ADVISE   
--> offer alternative.

If pilot receives clearance or instruction which cannot be complied with, advise ATC: UNABLE TO COMPLY + reason

Controllers will pass clearance slowly and clearly because pilot will need to write it down.   

Controllers should avoid passing a clearance to a pilot engaged in complicated taxiing maneuverrs and on non occasion should a clearance be passed when the pilot is engaged in line up or take-off maneuvers.   
E.g. route clearance should be passed to an aircraft before start up.

CONDITIONAL CLEARANCES: call sign - contidtion - clearance


level instructions may be reported as height, altitude, or flight level according to the altimeter pressure setting

QFE: altimeter subscale setting ~ 0 at airfield datum.    
QFE is measured at the highest point of the airfield surface; runway or helideck QFE dataum is measured at the threshold of the runway or helideck FATO.

QNH: altimeter subscale setting ~ altimeter above mean sea level AMSL := airfield elevation.

standard setting = 1013.2hPa (29.92in hg) = readout a pressure altitude or flight level; used for controlled airspace above transition level

clearances in some parts of the world are passed in metres. operators normally have metric altimeters fitted.   
Failing that operators provide conversion charts for meters to feet. If an altitude or height instruction is transmitted it must include the pressure setting.

ICAO manual of RTF includes the word "TO" in all climbing/descending instructions and the exam follows this convention.  
Most European countries do not use the word "TO" when transmitting instructions regarding Flight Levels

EXPEDITE ~~> climb/descent at the maximum possibe safe rate, commence maneuver immediately.

FL100 := FLIGHT LEVEL ONE HUNDRED, TWO HUNDRED ...

Flights joining airways -- clearance to join, conditions, etc.

leaving airway - specific point and instructions to ensure separation from other traffic

holding enroute - holding instruction, onward clearance time


### Routine Position Reporting

position reports, AIREPs, are required unless either the AIP or the ATS unit permit the pilot to omit them.   
It is normal to omit position reports when under radar control.

Position reports contain the following elements    
* ac identification
* position
* time
-------- can be omitted on the basis of regional air navigation agreements
* next position and time over
* ensuing significant point

Note: transmitting of time: by default "minutes-only", hour only to avoid confusion

### Filing Airborne Flight Plans

a pilot may file a flight plan with an ATS unit during flight.   
use of busy ATC channels should be avoided, normally FIR frequency should be used.  
Details should be passed using the flight plan format.

during flight, a pilot may change from IFR to VFR by cancelling the IFR flight plan.

when pilot has expressed the intention to change from IFR to VFR flight, the ATS unit should pass to the pilot any available meteoroglogical infromation that makes it likely that flight in VMC cannot be maintained.

### Radio Test Procedures - RADIO CHECK

test transmission:    
* identification of aeronautical station
* aircraft call sign
* RADIO CHECK
* frequency used

replies to include readability    
* identification of station calling
* identifcation of station replying
* information on readability

1   unreadable
2   readable now and then
3   readable, but with difficulty
4   readable
5   perfectly readable

when a ground station has to make test signals, such signals shall not continue for more than 10 seconds and shall be composed of splekn numbers, i.e., ONE, TWO, THREE, etc, followed by the radio call sign of the station transmitting the test signals.   
such transmissions should be kept to a minimum.


### Meteorological Observation by Aircraft

routine met observations are made at ATS reporting points roughly an hour apart or when requested.

ac exemptd from making routine observations when the flight duration is 2 hours or less, when the aircraft is wihin one hour of landing and when it is below 1500m (5000ft).

because position reports are omitted when under radar control and radar control is the norm over land this tends to mean that routine position reports contain met information mostly when operating in oceanic areas.   
The HF position report opposite includes the term OVER at the end of the transmission.

AIREP SPECIAL- special air reports shall be made by all aircraft whenever the following consitions are encoutered or observed:   

* moderate or severe turbulence
* moderate or severe icing
* severe mountain wave
* thunderstorms, without hail that are obscured, embedded, widespread or in squall lines
* thunderstorms with hai that are obscured, embedded, widespread, or in squall lines
* heavy duststorm or heavy sandstorm
* volcanic ash cloud
* re-eruption volcanic activity or a colcanic eruption

observations during climb of meteorological conditions or approach phases of flight not previously reported to the pilot-in-command which in his opinion are likely to affect the safety of other ac operations must be reporting in the AIREP format.   
AIREP shall be made as soon as possible.

AIREP content - 3 sections - 1st always sent, others when required

--> section 1
* aircraft identification
* position
* time
* flight level or altitude
* next position and ETA
--> section 2 --> operational information
* estimated time of arrival
* endurance
--> section 3 --> meteorological information
* air temperature
* wind
* turbulence
* aircraft icing
* supplementary information

when special AIREP of pre-eruption volcanic activity, a volcanic eruption or vlcanic ash cloud is transmitted the content and order in the AIRPE message is
(section 1): ac identification, position, time, FL/ALT
(section 3 - volcanic): VOLCANIC ACTIVITY OBSERVED, air temp, wind, supplementatial info


### Summary

flight either VFR or IFR. all flights can be IFR, but only some -- depending on WX and airspace -- can operate VFR.

first contact: full callsign, abbreviated call sign only after first use by ATC

words may be ommitted for   
* SURFACE ~ wind direction and speed
* DEGREES ~ radar headings
* VISIBILITY ~ cloud and height in met reports
* HECTOPASCALS ~ when issueing pressure settings

ALL ATC CLEARANCES MUST BE READ BACK ==> ensures clearance reception & transmission as intended

conditional clearance shall include the call sign, the condition, and the clearance.

ac requiring to join an airway should make their request to the appropriate ATS unit. Where no flight plan has been filed, the request should include the filing of an airborne flight plan.

Position reports are required unless either the AIP or the ATS unit permit the pilot to moti them. 
It is normal to omit position reports when under radar control.


## Standard Instructions

### Pre-Start Procedures

at aerodromes with no ATIS, aircrew may ask for current aerodrome information before requesting start-up.

aerodrome control service := air traffic control service for aerodrome traffic.    
aerodrome control radio station := station providing radio communication between an aerodrome control tower and aircraft or mobile aeronautical stations.

ac ~ (stand) position & acknowledgement of ATIS broadcast.

TWR will inform aircrew about any delay to the departure by providing start up or expected start up time.

start up := engine start, possibly assisted by ground crew

### Push-back

nose-in parking --> push-back before taxi    
requests for push back are made to ATC or apron control/management service depending on local procedures.

engines are normally started during push-back, i.e., request for start-up and pushback together.

```
aerodrome traffic := all traffic on the maneuvering area of an aerodrome and all aircraft flying in the vicinity of an aerodrome.   
apron := defined area, on a land aerodrome, intended to accommodate aircraft for the purpose of loading or unlaoding passengers, mail or cargo, fuelling, parking, or maintenance.
```

push-back coordinated between aircrew and ground crew via intercom.   
brakes must be off before push back starts

when push-back maneuver complete, ground crew give the pilot a visual signal to indicator that the aircraft is free to taxi.   
Pilot may stop maneuver at any stage: STOP PUSH-BACK.

```
maneuvering area := that part of an aerodrome to be used for take-off, landing, and taxiing of aircraft, excluding aprons.     

movement area := that part of an aerodrome to be used for take-off, landing, and taxiing of aircraft, consisting of maneuvering area AND aprons.
```

### Taxi Instructions

taxi instructions issued by a controller contains a **clearance limit** at which the aircraft must hold until a further permission to proceed is given (new clearance).

for departures: typically **holding point** of the runway in use, can be another position on the aerodrome depending on procedures and traffic

if ac acknowledges receipt of ATIS, ATCO does not need to provide the departure information when giving taxi instructions

```
Automatic Terminal Information Service (ATIS) := provision of  current, routine information, to arriving, and departing aircraft by means of continuous and repetivite broadcasts throughout the day or a specified portion of the day.
```

helicopters: "AIR TAXI"

### Take-Off Procedures

large aerodrome: separate GROUND and TOWER functions; ac transferred to TOWR at or approaching the holding point.

ac may be required to carry out checks prior to departure and are not always ready for take-off when they reach the holding point.    
READY FOR DEPARTURE upon completion of checks.

correct phraseology for taxi and take-off clearances to aovid misinterpretation and confusion.

```
holding point := a specified location, identified by visual or other means, in the vicinity of which the position or an aircraft in flight is maintained, in accordance with air traffic control clearances
```

LINE UP, RUNWAY XX

CLEARED FOR TAKE-OFF RUNWAY XX

### Take-Off Clearance

Take-off clearance: CALLSIGN CLEARD FOR TAKE-OFF RUNWAY XX   

if reduced runway separation is used to take-off clearance will be preceded by traffic information.     
Except in cases of emergency, controllers should not transmit to an aircraft in the process of taking off or in the early stages of a climb.

*immediate take-off clearance* ~ given traffic situation, aircraft to take-off immediately after lining up.

ARE YOU READY FOR IMMEDIATE DEPARTURE?

CLEARED FOR IMMEDIATE TAKE-OFF, RUNWAY XX.

### Departure Instruction

normally not provided by ATCO during taking off or early stage.   
ATC reoute clearance or local departure instruction are typically given when taxiing.

to aovid ambiguity with take-off clearance, DEPARTURE or AIRBORNE.

local departure instructions may also be given as part of the take-off clearance.

### Take-Off Clearance Not Actioned

TAKE-OFF IMMEDIATELY OR VACATE RUNWAY

### CANCELLING of a TAKE-OFF Clearance

unexpected traffic development or departing aircraft takes too long to take off, it may be necessary to cancel the take-off clearance and quickly free the runway.

CANCEL TAKE-OFF

### Abandoned Take-Off

ATC: STOP IMMEDIATELY, ... reason

if pilot/aircrew abandons take-off, the control tower should be informed as soon as practicable.

REJECTED TAKE-OFF, ... reason

### Joining the Circuit

request by aircraft for circuit -> joining instructions be made "sufficiently" in advance to allow a planned entry into the circuit, taking other traffic into account.

whenever the traffic circuit is a right-hand pattern, it will be specified in the clearance from ATC.   
A left-hand pattern = standard ~ not mentioned specifically or to avoid confusion.

when ATIS is provided, the pilot should acknowledge receipt of the broadcast in his initial call to the aerodrome

```
aerodrome traffic circuit := the specified path to be flown by aircraft operating in the vicinity of an aerodrome.
```

Following a request to join the circuit, aircraft may be instructed to join in three ways:

1. overhead join: overfly at 2000ft above aerodrome elevation, descend on the 'dead side' to circuit height, join circuit by crossing the upwind end of the runway at circuit height and then position downwind;
1. downwind join; or
1. join for a stright in approach

depending on prevailing traffic conditions and the direction from which an aircraft is arriving, it may be possible to give a straight-in approach.

pilot, after having joined the traffic circuit makes routine reports as required by local procedures.    
reporting procedures for a standard left hand circuit:   

* downwind
* late downwind, or in undable to report DONNWING and has passed the downwind end of runway
* BASE
* FINAL, clearance to land will be issued
* when aircraft is on straight-in approach: LONG FINAL

### Final Approach and Landing

FINAL report about 4NM/7km

turn to final wider out: LONG FINAL 15km/8NM   
if no landing clearance received a further call: FINAL at 7km/4NM from touchdown


### Request for Low Fly-by of the Tower

a pilot may request to fly past the control tower or other observation point, for the purpose of visual inspection from the ground.

if the low pass is made to allow air traffic to check the position of the gear the reply might use the words LANDING GEAR or WHEELS, for instance:

* landing gear appears down
* right wheel appears up
* wheels appear down
* nose wheel does not appear up.

### Request for Low Approach

for training purposes, a pilot may request permission to make an approach along or parallel to the runway without landing

### Request for Touch and Go

to save time when conducting training in the circuit, pilots may request to carry out a touch-and-go, i.e., the aircraft lands, continues rolling, and takes-off without stopping.

### ATC instruction to go-around

instructions to carry out a missed approach may be give to avert an unsafe situation.   
When a missed approach is initiated cockpit workload is inevitably high.   
Any transmissions to aircraft going around should be brief and kept to a minimum.

Unless instructions are issued to the contrary, an aircraft on an instrument approach will carry out the missed approach procedure and an aircraft operating VFR will continue in the normal traffic circuit.

If ATC require a go around they use the instruction; GO AROUND

### Pilot Initiated Go-Around

If the pilot initiates the missed approach the phrase: GOING AROUND is used.

### After Landing

Unless absolutely necessary, controllers should not give taxi instructions to pilots until the landing roll is complete.   
Pilots should remain on the tower frequency when clear of the runway unless otherwise advised.

### Summary

Where no ATIS is provided, you may ask for aerodrome information before requesting start-up.  
request start clearance.

Taxi instructions issued by a controller will always contain a clearance limit.

ATC route clearances and local departure instructions are often given whiles taxiing.   
The do no constitute a clearance to take off or enter an active runway.

To avoid ambiguity the phrase TAKE OFF is only used when an aircraft is cleared for take-off, or when cancelling a take-off clearance.

A FINAL report is made when an aircraft turns onto final within 7km/4NM from touchdown.   
For distance further than this position, a LONG FINAL report is made at about 15km/8NM from touchdown.   
If no landing clearance is received at that time, a further FINAL report is made at 7km/4NM from touchdown.

If ATC require a go around they will use the instruction GO AROUND.    
If the pilot initiates a go-around, the uses the phrase GOING AROUND.

Unless absolutely necessary, controllers should not give taxi instructions until the landing roll is complete.   
Aircraft should remain on Tower frequency - even when clear of the active runway - until instructed to change to Ground.



## Radar Procedures

communication between aircraft and "all types" of radar units.    
2 different radar services: i.) radar control, and ii.) advisory service.


### Radar Services

UNDER RADAR CONTROL ~ when radar conrol service = must comply with instructions from radar unit and ATC assumes responsibility for separation.

air traffic advisory service provides bearings, distance, and height information on known conflicting traffic.    
Some services will also provide advisory avoiding action.   
Pilot(s) remain(s) responsible for terrain and collision avoidance at all times.

A flight information service FIS is not a radar service.

### Radar Identification and Vectoring

radar vectors may be given to establish the identification of an aircraft.   
The aircraft may also be identified using position report information, by requesting the aircraft to make turns, by reported bearing and distance information from a prominent object or radio aid and the by use of SSR.

The pilot should be advised if radar identification is lost, or about to be lost, and appropriate instructions given.   

In a radar environment, heading information given by the pilot and heading instructions given by controllers are in defrees magnetic.

### Traffic Information and Avoiding Action

whenever practicale, infomration rgarding traffic on a conflicting path should be given in the following form:   

* relative bearing of the conflicting traffic in terms of the 12-hour clock;
* distance from the conflicting traffic;
* direction of flight of the conflicting traffic;
* level and type of aircraft or, if unknown, relative speed of the conflicting traffic, e.g. slow or fast.

Relative movement should be described by using whichever is appropriate of the following terms:   

* closing;
* converging;
* parallel;
* same direction;
* opposite direction;
* diverging;
* overtaking
* crossing left to right
* crossing right to left

Depending on the level of service, vectors may be offered by the controller or requested by the pilot.   
The controller should inform the pilot when the conflict no longer exists.

aircraft: LOOKING OUT FOR TRAFFIC; TRAFFIC IN SIGHT

### Radar Vectoring

Aircraft may be given specific vectors to fly to establish lateral separation.   
Unless it is self evident, pilots should be informed of the reasons why radar vectors are necessary.

When vectoring is completed, pilots shall be instructed to resume their own navigation and given position information and approprieate instruction as necessary.

Occasionally an aircraft may be instructed to make a complete turn - known as an orbit or a 360 degree turn - for delaying purposes or to achieve a required spacing behind preceding traffic.

### Secondary Surveillance Radar SSR

#### SSR Emergency Codes

Pilot not in direct communication with ATC should set the applicable special purpose code, preferably before any emergency transmissio is made, if the aircraft is qeuipped with an SSR transponder.

* mode A 7700   emergency
* mode A 7600   radio failure
* mode A 7500   hijack or unlawful interference

pilots in an emergency situation in contact with ATC and receiving a secondary service should maintain the code in use unless otherwise instructed.

The individual country's AIP will contain information of other special purpose SSR codes, if any.

ATC instructions with respect to SSR transponders

* SQUAWK xxxx     set mode A code as instructed
* CONFIRM SQUAWK  confirm mode A code set on the transponder
* RESET xxxx      reselect assigned mode A code
* SQUAWK IDENT    operate te IDENT feature
* SQUAWK MAYDAY   select the emergency code
* SQUAWK STANDBY  select the standby feature
* SQUAWK CHARLIE  select pressure altitute transmission
* CHECK ALTIMETER SETTING AND CONFIRM LEVEL check pressure setting and confirm present level
* STOP SQUAWK CHARLIE WRONG INDICATOR
* RESET MODE S INDICATION for a mode S equipped aircraft, check the setting of the aircraft identification
* VERIFY LEVEL (used to derive accuracy of the Mode C level information displayed to the controller) check and confirm your level.

pilot's reply to SSR instructions is usually either an acknowledgement or read back.   
If ATC ask for your transponder capability ==> resply with a combination of Mode A, C, and/or S depending on the type of transponder fitted.


### Approach Control

#### VFR Departures

Departing VFR traffic - when handled by an approach control unit 0 may be passed infromation on relevant traffic under an advisory service in order to assit the pilits in maintaining their own separation.

Pilot should report leaving the area of responsibility of the approach control unit.

Aerodromes may permit special VFR arrivals and departures.   
SVFR procedures will be published in the AIP.

#### IFR Departures

typically, one approach control unit handles both approach and departures.   
At busier airports, departures and arrivals may be handled separately by specific arrival and departure control units.

In addition to the ATC route clearance, departing IFR flights may be given departure instructions by departure control.    
These may be given in plain language or in the form of a standard instrument departure SID.

#### VFR Arrivals

depending on the procedures in use, the pilot of an arriving VFR flight may be required to establish contact with the approach control unit and request instructions before enterin its area of responsibility.

Where there is an ATIS broadcast, the pilot should acknowledge if it has been received.   
Where no ATIS broadcast is provided the approach controller will pass the aerodrome data.

#### IFR Arrivals

Approach control will normally advise on intial contact the type of approach to be expected.

Occasionally, IFR aircraft do not complete the instrument approach procedure but request permission to make a visual approach.   
A request for a visual approach does not imply that the aircraft is flying in VMC but only that the specified requirements for a visual approach have been met and that the pilot can maintain visual reference to the terrain.

### HOlding

Normally a holding procedure should be published.   
However, when the pilot requires a detailed description of the holding procedure based on a facility, the information should be passed in the following order:

* fix;
* level;
* inbound track;
* right or left turns;
* time of leg (if necessary)

### Radar Vectors to Final Approach

radar vectors are given to arriving flights to position them onto a pilot-interpreted final approach aid, or to a point from which a radar assisted approach can be made, or to a point from whtih a visual approach can be made.

possible speed control to establish separation.

### Surveillance Radar Approach

on a surveillance radar approach SRA the pilot is given distances from touchdown, advisory altitude or height information and zimuth instructions, in order to carry out an approach.   
SRAs are moe likely to be available at military aerodromes than at civilian ones, and the military usually uses QFE rather than QNH ??????

where SRA procedure terminates at 2 miles from touchdown, the distance from touchdown and advisory altitude checks are normally passed at 1 mile intervals.   
Where the DRA terminates at less than 2 miles from touchdown, such checks are given each half mile.

Aircraft replies are expected to all transmissions up to the point where the pilot is instructed not to reply.

Pilot to report RUNWAY IN SIGHT
--> CONTINUE VISUALLY (IF RUNWAY NOT IN SIGHT GO AROUND)

### Precision Radar Approach

PAR controller, in addition to providing heading instructions during the continuous talkdown, provides information on altitudes relateive to the glide slope, together with instructions on corrective action in the event that the aircraft is too high or too low.

when radar returns on the elevation element of the PAR indicate that the pilot may be making a missed approach, the radar controller shall, when there is sufficient time to obtain a reply from the pilot, pass the aircrafts height above the glide path and ask the pilot if a missed approach is intended.

in similar circumstances, but when there is not sufficient time to obtain a replay from the pilot, the ATCO should continue the preceision approach empahsising the ac displacement.   
If it becomes apparent that the pilot is mmaking a missed approach, eith before or after the normal termination point, the radar controller shall pass missed approach instructions.

### Summary

There are 2 different types of radar services: i.) radar control, and ii.) advisory service.

The pilot remains responsible for terrain and collision avoidance at all times.   
A flight infomration services FIS is  not a radar service.

In a radar environment, heading information given by the pilot and heading instructions given by the controllers are in degrees magnetic.

Whenever practicalble information regarding conflicting traffic should be given dtailing the relative bearing and distance of the traffic, its direction of flight, level and type of aircraft or, if unknown, relateive speed and whether it is slow or fast moving, same level, parallel, converging or crossing.

SSR emergency codes are Mode A 7700 "emergency", 7600 " radio failure", and 7500 "hijack or unlawful interference".    
Pilots in an emergency situation in contact with ATC and receiving secondary service should maintain the code in use unless other wise instructed.

Typically, a single approach control unit handles both VFR and IFR arrivals and departures.   
At busier airports, departures and arrivals may be handled separately by specific arrival and departure control units.

